[theme]
base = "light"
primaryColor = "#2563EB"
backgroundColor = "#F3F6FC"
secondaryBackgroundColor = "#E9EFF9"
textColor = "#142748"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
